/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import gestionexamen.Utilisateurs;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import org.jasypt.util.password.ConfigurablePasswordEncryptor;
import org.jasypt.util.password.StrongPasswordEncryptor;

/**x vf
 *
 * @author Euvince
 */
public class RegisterForm extends javax.swing.JFrame {

    private final EntityManagerFactory emf = javax.persistence.Persistence.createEntityManagerFactory("GestionExamenPU");
    
    private final EntityManager entityManager = emf.createEntityManager();
    
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }
    
    private boolean estFormatEmailValide(String email) {
        // Utiliser une expression régulière pour valider le format de l'e-mail
        String regex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Z|a-z]{2,}$";
        return email.matches(regex);
    }
    
    private boolean estMotDePasseSecurise(String motDePasse) {
        // Au moins 8 caractères, une majuscule, au moins un caractère spécial, au moins deux chiffres
        String regex = "^(?=.*[A-Z])(?=.*\\d.*\\d)(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\"\\\\|,.<>\\/?]).{8,}$";
        return motDePasse.matches(regex);
    }

    
    public void register () {
        try {
            if (
                registeremailtxt.getText().isEmpty() || 
                new String(registerpasswordtxt.getPassword()).isEmpty()
            ){
                JOptionPane.showMessageDialog(null, "Remplissez tous les champs s'il vous plaît.");
            }
            else if (
                !registeremailtxt.getText().isEmpty() && 
                !estFormatEmailValide(registeremailtxt.getText())
            ){
                JOptionPane.showMessageDialog(null, "Le format de l'email est invalide.");
            }
            else if (
                !new String(registerpasswordtxt.getPassword()).isEmpty() && 
                !estMotDePasseSecurise(new String(registerpasswordtxt.getPassword()))
            ){
                JOptionPane.showMessageDialog(null, "Le Mot de passe doit contenir au moins 8 caratères, une majuscule, un caractère spécial et au moins  02chiffres.");
            }
            else {
                Utilisateurs user = new Utilisateurs();
                user.setEmail(registeremailtxt.getText());

                char[] EnterPassword = registerpasswordtxt.getPassword();
                String passwordFormat = new String(EnterPassword);
                ConfigurablePasswordEncryptor textEncryptor = new ConfigurablePasswordEncryptor();

                user.setMdp(textEncryptor.encryptPassword(passwordFormat));

                entityManager.getTransaction().begin();
                entityManager.persist(user);
                entityManager.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Nouvel Utilisateur enrégistré avec succès");
                LoginForm lf = new LoginForm();
                lf.setVisible(true);
                lf.setLocationRelativeTo(null);
                lf.pack();
                this.dispose();
            }
        }catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Échec de l'enrégistrement de l'utilisateur");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Left1 = new javax.swing.JPanel();
        Right1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        registeremailtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        registerpasswordtxt = new javax.swing.JPasswordField();
        registerbutton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        goToLogin = new javax.swing.JButton();
        registerexit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Left1.setBackground(new java.awt.Color(51, 153, 255));
        Left1.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout Left1Layout = new javax.swing.GroupLayout(Left1);
        Left1.setLayout(Left1Layout);
        Left1Layout.setHorizontalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Left1Layout.setVerticalGroup(
            Left1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Right1.setBackground(new java.awt.Color(255, 255, 255));
        Right1.setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 153, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CRÉER UN COMPTE");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        registeremailtxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registeremailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registeremailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeremailtxtActionPerformed(evt);
            }
        });
        registeremailtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                registeremailtxtKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mot de Passe");

        registerpasswordtxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerpasswordtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        registerpasswordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                registerpasswordtxtKeyReleased(evt);
            }
        });

        registerbutton.setBackground(new java.awt.Color(255, 255, 255));
        registerbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(0, 153, 255));
        registerbutton.setText("Soumettre");
        registerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbuttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Vous avez déjà un compte ?");

        goToLogin.setBackground(new java.awt.Color(255, 255, 255));
        goToLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(0, 153, 255));
        goToLogin.setText("Login");
        goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginActionPerformed(evt);
            }
        });

        registerexit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerexit.setText("X");
        registerexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerexitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Right1Layout = new javax.swing.GroupLayout(Right1);
        Right1.setLayout(Right1Layout);
        Right1Layout.setHorizontalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Right1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                    .addComponent(goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(registeremailtxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(registerpasswordtxt, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(registerbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Right1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(registerexit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Right1Layout.setVerticalGroup(
            Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Right1Layout.createSequentialGroup()
                .addComponent(registerexit)
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registeremailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Right1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Right1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(registerpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(registerbutton)
                        .addGap(69, 69, 69)
                        .addComponent(jLabel8))
                    .addComponent(goToLogin))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Left1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(Right1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Right1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Left1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registeremailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeremailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registeremailtxtActionPerformed

    private void registerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbuttonActionPerformed
        register();
    }//GEN-LAST:event_registerbuttonActionPerformed

    private void goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginActionPerformed
        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.setLocationRelativeTo(null);
        lf.pack();
        this.dispose();
    }//GEN-LAST:event_goToLoginActionPerformed

    private void registerexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerexitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_registerexitMouseClicked

    private void registerpasswordtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registerpasswordtxtKeyReleased
        char[] passwordText = registerpasswordtxt.getPassword();
        String pwd = new String(passwordText);
        if (estMotDePasseSecurise(pwd)) {
            registerpasswordtxt.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        } else {
            registerpasswordtxt.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        /*champsNonVides();*/

    }//GEN-LAST:event_registerpasswordtxtKeyReleased

    private void registeremailtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_registeremailtxtKeyReleased
        if (estFormatEmailValide(registeremailtxt.getText())) {
            registeremailtxt.setBorder(BorderFactory.createLineBorder(Color.GREEN));
        } else {
            registeremailtxt.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

        /*champsNonVides();*/
    }//GEN-LAST:event_registeremailtxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegisterForm rf = new RegisterForm();
                rf.setVisible(true);
                rf.setLocationRelativeTo(null);
                rf.pack();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left1;
    private javax.swing.JPanel Right1;
    private javax.swing.JButton goToLogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton registerbutton;
    private javax.swing.JTextField registeremailtxt;
    private javax.swing.JLabel registerexit;
    private javax.swing.JPasswordField registerpasswordtxt;
    // End of variables declaration//GEN-END:variables
}
